# Generated by Django 5.0.4 on 2024-09-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CivisTrack_App', '0002_category_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('sante', 'Santé'), ('securite', 'Sécurité'), ('education', 'Éducation'), ('administration', 'Administration'), ('restaurants', 'Restaurants'), ('loisirs', 'Loisirs'), ('centres-commerciaux', 'Centres Commerciaux'), ('hotels', 'Hôtels'), ('banques', 'Banques')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
