# Generated by Django 5.0.4 on 2024-09-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CivisTrack_App', '0004_alter_category_name_alter_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.TextField(default=''),
        ),
    ]
